### ISSUE TITLE
Change name from SPlayer, there already is an SPlayer, I suggest the name Sugoi Player instead

### ISSUE THREAD

**Issue by yetisyny** [wangwenx190/sugoi-player-deprecated#1]
There already exists a media player called SPlayer. Look at [https://www.splayer.org/](https://www.splayer.org/) or its repository at [https://github.com/tomasen/splayer](https://github.com/tomasen/splayer).

You should change the name of your media player to something else that is unique, that is not the name of another media player which already exists.

I have a suggestion for a name, you can call it Sugoi Player. Sugoi means “amazing” or “awesome” and is also used as a loanword from Japanese just like baka (“stupid”) and kawaii (“cute”) as part of otaku culture. Plus Sugoi starts with the letter S just like SPlayer.

Sugoi Player would be a really good name for a media player, and nobody else is using that name yet, but people are using the name SPlayer already so you should probably change it or else they will get your SPlayer mixed up with the other SPlayer.

Other open-source software has had to change its name too. Mozilla Firefox was originally called Mozilla Phoenix but another program was called Phoenix, then they changed their name to Mozilla Firebird but another program was called Firebird, so eventually they picked the name Firefox since nobody else was using it. Just like nobody uses the name Sugoi Player. Better to change the name sooner rather than later, I think the name SPlayer might have a trademark and the sooner you get people used to a new name the better.

Or you could pick a different name, any name that nobody else is using, I just like the name Sugoi Player and think it would be appropriate for this project, it is just a suggestion.

**Comment by wangwenx190** [comment]
Good suggestion, thanks. In fact, "SPlayer" is just a temporary name, but I cannot think of another satisfying name, you really helped me a lot. Actually, I have already known that there is a media player called SPlayer (the one you mentioned), I used it as my favorite media player for quite a while, it's a great media player. I changed my favorite media player to MPC-HC after SPlayer stops updating. I will use "Sugoi Player" instead, it's a good name indeed, thanks. But there are so many "SPlayer" words in the whole repository, so it may take a few days to completely rename it. It seems that you are quite familiar with SPlayer (the one you mentioned) and Baka MPlayer, may I ask are you one the contributors (or users) of SPlayer or Baka MPlayer? English is not my native language, sorry for the poor English.

**Comment by yetisyny** [comment]
No, sorry, I am not a contributor to those projects. I was recently trying to document all of the media players that use mpv and I have been editing the Wikipedia page of mpv a lot, I contribute to the Wikipedia project. See [https://en.wikipedia.org/wiki/Mpv_(media_player)](https://en.wikipedia.org/wiki/Mpv_(media_player)).

The entire section of that article about front-ends for mpv, I wrote it and did all the research for it. I was researching mpv front-ends when I came across yours, since I wanted to document them all. I did not actually add yours to the list because it is too new, has not had a stable release yet, had the same name as another project which people would find confusing, and I do not really know how the goal of your project is different from the goals of the other front-end projects.

Anyway the reason I know these things is I was researching them so that I could write for an article about it on Wikipedia, I think I did a pretty good job of it. I am not a developer on any of them. I am pretty good at writing for Wikipedia articles, though. It is a free encyclopedia anyone can edit, and I do my part to help improve it whenever I see the need for it. I use Wikipedia to learn many things, but when a Wikipedia article is not good enough for my standards, I do some research and improve the article.

By the way, your English is very very good. I have studied several languages and I am nowhere near as good as you are in any of them, except for English. But it is my native language so of course I know it, everyone knows their native language. It is learning second and third languages that requires effort. You are better at that than I am.

Guess what language I am trying to learn right now? German! I have some family in Austria, where people speak German. It is inconvenient when I visit because I cannot speak the language people in Austria speak. My current level of German is much, much worse than your level of English. I get the pronunciation, grammar, and everything else wrong, and have a very tiny vocabulary. You do not have to apologize for your English. Millions of people in the United States are not as good at having proper English grammar and spelling as you are. I know plenty of them. You should be more confident about your English skills. You definitely do a better job expressing yourself in English than the computer program Google Translate, which makes a lot of mistakes.

One last thing: Baka MPlayer seems to be the only mpv front-end that supports all 3 major desktop operating systems: Windows, macOS, and Linux. I myself have used all 3 of those operating systems, I am typing this in macOS right now. All the other mpv front-ends either only support one operating system, or support Windows and Linux but not macOS. Baka MPlayer has not had any development in over a year, since January of last year, which is sad. But you have forked the project and are continuing its work! I hope you can build on its work and get everything up-to-date. Mpv is better than ever now. I thought mpv was going to leave VLC Media Player in the dust last year, but VLC Media Player recently came out with version 3 earlier this month with a lot of improvements so it is still competitive. However, most people dislike VLC’s interface, whereas mpv has a whole bunch of neat interfaces to pick from, all of these wonderful front-ends. Personally the front-end I use is IINA, since I mainly use a Mac, and that is the only one specifically designed for Macs. But on a Windows or Linux computer, I don’t know which front-end for mpv I would use. So many to choose from...

Oh right, and it seems the Baka MPlayer developers quit working on it to develop a new player, mochi-player, but there is no public evidence of them working on it since June of last year. Maybe they are secretly working on it behind the scenes and just not putting the source code online. I have no idea. Anyway it is supposedly supposed to be the successor to Baka MPlayer but it doesn’t work yet, from what I read. I am not a developer on any of these projects, I just researched this to write about it on Wikipedia. And why did I do that? Because I think mpv is one of the best video players ever and has great front-ends and I wanted to give it a better article that talked about all of that to encourage people to use it. Neither your new player nor the mochi-player is on the list on Wikipedia of front-ends since I only listed ones that already have stable releases that people are already using.

**Comment by wangwenx190** [comment]
Thanks very much for such a good article. What you have done is really encouraging. Maybe you do not know [bomi](http://bomi-player.github.io/), it's also a beautiful and powerful mpv front-end, I really like it. It supports both Windows and Linux. But it seems that it does not support macOS. So sad about it. As for IINA, I know it as well. It's developer is a Chinese and it has a beautiful interface, that's all I know. As for Wikipedia, I know it of course. I am a Chinese, and maybe you do not know that our government has blocked it as well as Google. But I can still access these "illegal" websites using VPN. Wikipedia and Google are so famous that everyone on earth should know them. And we Chinese have to begin studying English from a very early age, our college entrance examination will also take an examination of English, so maybe it's a bit different from self-learning. You are really "Sugoi", ha ha. Anyway, it's so good to know you.

**Comment by wangwenx190** [comment]
My player only supports Windows because I only work on Windows currently, maybe it will also support Linux and macOS in the future. Who knows :)
