### ISSUE TITLE
Feature Request remember player window size on windowed

### ISSUE THREAD

**Issue by wingedonezero** [wangwenx190/sugoi-player-deprecated#3]
Allow to remember windows size on windowed for all future and previous media. Instead of resizing on new media or previous.

**Comment by wangwenx190** [comment]
I will rewrite the whole repository completely using Qt Quick instead of Qt Widgets and the new player will no longer base on Baka MPlayer. Your suggestions are good to me and I will add these functions to the new player. The old Sugoi Player will be deprecated.
